#!/bin/bash

BASE=`whoami`
PREFIX=$BASE/kernel.log
OUTFILE=$PREFIX.out
PARSE=./parse.awk
DOTDOT=./dotdot

parselog() {
  echo -n 'Parsing' $1
  $PARSE $1 >> $OUTFILE &
  $DOTDOT $!
}

# Clean up the data directory.
if [ -d $BASE ]; then
  echo 'Removing dataset' $BASE
  rm -r -f $BASE
fi
echo 'Creating dataset' $BASE
mkdir $BASE

# Copy over logs and run awk script.
cp /var/log/kernel.log $BASE
cp /var/log/kernel.log.*.bz2 $BASE
bunzip2 $PREFIX.*.bz2

parselog $PREFIX
for ((i = 0; i <= 5; i++)); do
  parselog $PREFIX.$i
done

echo 'Done!'
