#!/bin/bash

PREFIX=kernel.log
OUTFILE=$PREFIX.out
PARSE=./parse
DOTDOT=./dotdot

parselog() {
  echo -n 'Parsing' $1
  $PARSE $1 >> $OUTFILE &
  $DOTDOT "$!"
}

if [ -e $OUTFILE ]; then
  echo 'Removing outfile.'
  rm -f $OUTFILE
fi

parselog $PREFIX
for ((i = 0; i <= 5; i++)); do
  parselog $PREFIX.$i
done

echo 'Done!'
